
version: '3.5'
services:
  redis:
    container_name: redis
    image: redis
    expose:
      - 6379
      
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=${REDIS_HOSTS_COMMANDER}
    ports:
    - "8081:8081"
      
  workerui:
    restart: always
    environment:
      - REDIS_HOSTS=${REDIS_HOSTS_WORKUI}
    build:
        context: .
        dockerfile: Dockerfile.worker
    ports:
      - "8181:8181"